In [ ]:
#arithmatic operation in numpy
import numpy as np
ar1=np.array([10,11,12,13,14])
ar=np.array([4,6,7,8,8])
new=np.add(ar1,ar)
print(new)

[14 17 19 21 22]


In [ ]:
#subtraction of array
ar1=np.array([10,11,12,13,14])
ar=np.array([4,6,7,8,3])
new=np.subtract(ar1,ar)
print(new)

[ 6  5  5  5 11]


In [ ]:
#divide of the array
ar1=np.array([10,11,12,13,14])
ar=np.array([4,6,7,8,3])
new=np.divide(ar1,ar)
print(new)

[2.5        1.83333333 1.71428571 1.625      4.66666667]


In [ ]:
#modulas of array
ar1=np.array([10,11,12,13,14])
ar=np.array([4,6,7,8,3])
new=np.mod(ar1,ar)
print(new)

[2 5 5 5 2]


In [ ]:
#multiplication of

ar1=np.array([10,11,12,13,14])
ar=np.array([4,6,7,8,8])
new=np.multiply(ar1,ar)
print(new)

[ 40  66  84 104 112]


In [ ]:
#multiplication of

ar1=np.array([10,11,12,13,14])
ar=np.array([4,6,7,8,8])
new=np.multiply(ar1,ar)
print(new)

In [ ]:

#addition of arrays
ar1=np.array([10,11,12,13,14])
ar=np.array([4,6,7,8,8])
add_ans=ar1+ar
print(add_ans)

[14 17 19 21 22]


In [ ]:

#subtraction of arrays
ar1=np.array([10,11,12,13,14])
ar=np.array([4,6,7,8,8])
sub_ans=ar1-ar
print(sub_ans)

[6 5 5 5 6]


In [ ]:

#multiplication of arrray
ar1=np.array([10,11,12,13,14])
ar=np.array([4,6,7,8,8])
mul_ans=ar1*ar
print(mul_ans)

[ 40  66  84 104 112]


In [ ]:
#add by using add function 
a=np.arange(9).reshape(3,3)
print(a)
print("\n")
b=np.array([2,2,2])
print(b)
print("\n")
print(np.add(a,b))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[2 2 2]


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
a3=np.arange(18).reshape(3,2,3)
print(a3)
print("\n")
b=np.arange(9).reshape(3,1,3)
print(b)
print("\n")
print(np.add(a3,b))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


[[[0 1 2]]

 [[3 4 5]]

 [[6 7 8]]]


[[[ 0  2  4]
  [ 3  5  7]]

 [[ 9 11 13]
  [12 14 16]]

 [[18 20 22]
  [21 23 25]]]


In [ ]:
#statistical function
ar1=np.array([10,11,12,13,14,5,6,7,2,3])
print(np.amin(ar1),np.amax(ar1))

2 14


In [ ]:
ar1=np.array([50.3,30.2,40.2,60.5,70.7,80.9,99.9])
print(np.percentile(ar1,70))

72.74


In [ ]:
ar1=np.array([10,11,12,13,14,5,6,7,2,3])
print(np.mean(ar1))

8.3


In [ ]:
ar1=np.array([10,11,12,13,14,5,6,7,2,3])
print(np.median(ar1))

8.5


In [ ]:
ar1=np.array([10,11,12,13,14,5,6,7,2,3])
print(np.std(ar1))

4.050925820105819


In [ ]:
ar1=np.array([10,11,12,13,14,5,6,7,2,3])
print(np.amin(ar1))