In [1]:
import numpy as np
a=np.array([1,2,3])
new=np.cumsum(a)
print(new)

[1 3 6]


In [4]:
import numpy as np
a=np.array([1,2,3])
new=np.cumprod(a)
print(new)

[1 2 6]


In [8]:
a=np.array([1,2,3,4,5,6,7,8,9,90])
b=np.array([2,3,4,523,34,5,67,89])
print(a)
print("\n")
np.logical_and(a>1,a<5)

[ 1  2  3  4  5  6  7  8  9 90]




array([False,  True,  True,  True, False, False, False, False, False,
       False])

In [12]:
#set functions
a=np.arange(1,18)
print(np.unique(a))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [16]:
a=np.arange(1,14)
b=np.arange(14,15)
print(a)
print("\n")
new=np.union1d(a,b)
print(new)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13]


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [17]:
a=np.array([1,2,34,5])
b=np.array([3,4,5,6,7])
n=np.intersect1d(a,b,assume_unique=True)
print(n)

[5]
