In [ ]:
#sorting of one d array
import numpy as np
a=np.array([5,6,73,2,76342,2,46,3,1])
b=np.sort(a)
print(b)


[    1     2     2     3     5     6    46    73 76342]


In [ ]:
#sorting of 2d array
a=np.array([[3,45,67,1,32],[33,445,5,32,7]])
b=np.sort(a)
print(b)

[[  1   3  32  45  67]
 [  5   7  32  33 445]]


In [ ]:
#character array sorting
a=np.array(['a','k','z','l'])
b=np.sort(a)
print(b)

['a' 'k' 'l' 'z']


In [ ]:
a=np.array(['johan','rakhi','hai','chhutti','do'])
b=np.sort(a)
print(a)

['johan' 'rakhi' 'hai' 'chhutti' 'do']


In [2]:
#sorting of one d arrray
import numpy as np
a=np.array([32,3,4,5,23])
print('original array is:',a)
print('sorted array is:',np.sort(a))

original array is: [32  3  4  5 23]
sorted array is: [ 3  4  5 23 32]


In [3]:
#descending order numpy array
a=np.array([32,3,4,5,23])
a[::-1].sort()
print(a)

[32 23  5  4  3]


In [7]:
#sorting in 2d numpy array
a=np.array([[3,45,67,1,32],[33,445,5,32,7]])
print("with None\n",np.sort(a,axis=None))
print("\n")
print("with axis 1 collumn \n",np.sort(a,axis=1))
print("\n")
print("with axis 0 row\n",np.sort(a,axis=0))

with None
 [  1   3   5   7  32  32  33  45  67 445]


with axis 1 collumn 
 [[  1   3  32  45  67]
 [  5   7  32  33 445]]


with axis 0
 [[  3  45   5   1   7]
 [ 33 445  67  32  32]]


In [13]:
#3d array sorting with None ,1,0
new_arr = np.array([[ 78,  23,  41,  66],
              [ 109,  167,  41,  28],
              [ 187, 22, 76, 88]])
b = new_arr.reshape(3, 2, 2)
print("b=",b)
print("\n")
print("By axis b=",np.sort(b,axis=None))
print("\n")
print("By 0 b=",np.sort(b,axis=0))
print("\n")
print("By 1 b=",np.sort(b,axis=1))

b= [[[ 78  23]
  [ 41  66]]

 [[109 167]
  [ 41  28]]

 [[187  22]
  [ 76  88]]]


By axis b= [ 22  23  28  41  41  66  76  78  88 109 167 187]


By 0 b= [[[ 78  22]
  [ 41  28]]

 [[109  23]
  [ 41  66]]

 [[187 167]
  [ 76  88]]]


By 1 b= [[[ 41  23]
  [ 78  66]]

 [[ 41  28]
  [109 167]]

 [[ 76  22]
  [187  88]]]


In [20]:
#aplying sorting algorithms
array=[5,6,73,2,76342,2,46,3,1]
a=np.sort(array,kind='slectionsort')
print(a)
b=np.sort(array,kind='mergesort')
print("\n")
print(b)
c=np.sort(array,kind='quicksort')
print("\n")
print(c)
d=np.sort(array,kind='heapsort')
print("\n")
print(d)


[    1     2     2     3     5     6    46    73 76342]


[    1     2     2     3     5     6    46    73 76342]


[    1     2     2     3     5     6    46    73 76342]


[    1     2     2     3     5     6    46    73 76342]
